// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/ardafirdausr/kaseer/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, param
func (_m *ProductRepository) Create(ctx context.Context, param entity.CreateProductParam) (*entity.Product, error) {
	ret := _m.Called(ctx, param)

	var r0 *entity.Product
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateProductParam) *entity.Product); ok {
		r0 = rf(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, entity.CreateProductParam) error); ok {
		r1 = rf(ctx, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DecrementProductByIDs provides a mock function with given fields: ctx, IDDecrementMap
func (_m *ProductRepository) DecrementProductByIDs(ctx context.Context, IDDecrementMap map[int64]int) error {
	ret := _m.Called(ctx, IDDecrementMap)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[int64]int) error); ok {
		r0 = rf(ctx, IDDecrementMap)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByID provides a mock function with given fields: ctx, ID
func (_m *ProductRepository) DeleteByID(ctx context.Context, ID int64) (bool, error) {
	ret := _m.Called(ctx, ID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllProducts provides a mock function with given fields: ctx
func (_m *ProductRepository) GetAllProducts(ctx context.Context) ([]*entity.Product, error) {
	ret := _m.Called(ctx)

	var r0 []*entity.Product
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Product); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBestSellerProducts provides a mock function with given fields: ctx
func (_m *ProductRepository) GetBestSellerProducts(ctx context.Context) ([]*entity.ProductSale, error) {
	ret := _m.Called(ctx)

	var r0 []*entity.ProductSale
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.ProductSale); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ProductSale)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductByCode provides a mock function with given fields: ctx, code
func (_m *ProductRepository) GetProductByCode(ctx context.Context, code string) (*entity.Product, error) {
	ret := _m.Called(ctx, code)

	var r0 *entity.Product
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Product); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductByID provides a mock function with given fields: ctx, ID
func (_m *ProductRepository) GetProductByID(ctx context.Context, ID int64) (*entity.Product, error) {
	ret := _m.Called(ctx, ID)

	var r0 *entity.Product
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Product); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductsByIDs provides a mock function with given fields: ctx, IDs
func (_m *ProductRepository) GetProductsByIDs(ctx context.Context, IDs ...int64) ([]*entity.Product, error) {
	_va := make([]interface{}, len(IDs))
	for _i := range IDs {
		_va[_i] = IDs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*entity.Product
	if rf, ok := ret.Get(0).(func(context.Context, ...int64) []*entity.Product); ok {
		r0 = rf(ctx, IDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...int64) error); ok {
		r1 = rf(ctx, IDs...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: ctx, ID, param
func (_m *ProductRepository) UpdateByID(ctx context.Context, ID int64, param entity.UpdateProductParam) (bool, error) {
	ret := _m.Called(ctx, ID, param)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int64, entity.UpdateProductParam) bool); ok {
		r0 = rf(ctx, ID, param)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, entity.UpdateProductParam) error); ok {
		r1 = rf(ctx, ID, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
