// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/ardafirdausr/kaseer/internal/entity"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// UserUsecase is an autogenerated mock type for the UserUsecase type
type UserUsecase struct {
	mock.Mock
}

// GetUserByCredential provides a mock function with given fields: ctx, credential
func (_m *UserUsecase) GetUserByCredential(ctx context.Context, credential entity.UserCredential) (*entity.User, error) {
	ret := _m.Called(ctx, credential)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserCredential) *entity.User); ok {
		r0 = rf(ctx, credential)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, entity.UserCredential) error); ok {
		r1 = rf(ctx, credential)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, ID
func (_m *UserUsecase) GetUserByID(ctx context.Context, ID int64) (*entity.User, error) {
	ret := _m.Called(ctx, ID)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.User); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveUserPhoto provides a mock function with given fields: ctx, user, file
func (_m *UserUsecase) SaveUserPhoto(ctx context.Context, user *entity.User, file *multipart.FileHeader) (string, error) {
	ret := _m.Called(ctx, user, file)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User, *multipart.FileHeader) string); ok {
		r0 = rf(ctx, user, file)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entity.User, *multipart.FileHeader) error); ok {
		r1 = rf(ctx, user, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, ID, param
func (_m *UserUsecase) UpdateUser(ctx context.Context, ID int64, param entity.UpdateUserParam) (bool, error) {
	ret := _m.Called(ctx, ID, param)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int64, entity.UpdateUserParam) bool); ok {
		r0 = rf(ctx, ID, param)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, entity.UpdateUserParam) error); ok {
		r1 = rf(ctx, ID, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserPassword provides a mock function with given fields: ctx, ID, password
func (_m *UserUsecase) UpdateUserPassword(ctx context.Context, ID int64, password string) (bool, error) {
	ret := _m.Called(ctx, ID, password)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) bool); ok {
		r0 = rf(ctx, ID, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, ID, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
